name: dashatar_flutter_example
description: Example app for dashatar_flutter package
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dashatar_flutter:
    path: ../
  intuosol_design_system: ^0.3.0
  widget_snippet: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
