name: Build & Deploy Example App

on:
  # Disabled for manual running of the workflow
  workflow_dispatch:

#  push:
#    branches: [main]
#    paths:
#      - 'example'
#      - '!**.md' # ignore the readme files

jobs:
  build-and-deploy:
    name: "Build & Deploy web app"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Debug directory structure before setup
        run: |
          echo "Checking initial directory structure..."
          ls -la
          ls -la assets/ || echo "No assets directory found yet"

      - name: "Install Flutter and Dart SDK"
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: "Show Flutter SDK version"
        run: flutter --version

      - name: "Flutter enable Web"
        run: flutter config --enable-web

      - name: "Get dependencies for package"
        run: flutter pub get

      - name: "Debug asset structure after package dependencies"
        run: |
          echo "Checking assets after package dependencies..."
          ls -la
          ls -la assets/ || echo "No assets directory yet"
          ls -la assets/dashatars/ || echo "No dashatars directory yet"
          ls -la assets/dashatars/Designer/ || echo "No Designer directory yet"
          ls -la assets/dashatars/Developer/ || echo "No Developer directory yet"
          ls -la assets/dashatars/Manager/ || echo "No Manager directory yet"

      - name: "Flutter clean before build"
        run: |
          flutter clean
          cd example
          flutter clean

      - name: "Get dependencies for example"
        run: flutter pub get
        working-directory: example

      - name: "Show outdated packages"
        run: flutter pub outdated

      - name: "Create web directory"
        run: |
          cd example
          flutter create --platforms=web .

      - name: "Debug pubspec.yaml content"
        run: |
          echo "Main package pubspec.yaml:"
          cat pubspec.yaml
          echo "Example pubspec.yaml:"
          cat example/pubspec.yaml

      - name: "Build web app"
        run: |
          cd example
          flutter build web --base-href='/dashatar_flutter/'

      - name: "Deploy web app"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: "example/build/web"
          single-commit: true
